name: Workflow de Integração Contínua
permissions:
  contents: read

on:
  push:
    branches: [ "main",  "develop"]
  pull_request:
    branches: [ "main",  "develop"]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.
    - run: npm install
    - run: npm test
